#!/usr/bin/env bash

commit_msg_file="$1"
commit_source="$2"

if [[ $commit_source == "merge" ]]; then
	mapfile -t lines <"$commit_msg_file"
	lines[0]="chore: merge ${lines[0]#Merge }"
	printf '%s\n' "${lines[@]}" >"$commit_msg_file"
fi
