---
name: Setup Test Environment
description: Setup Git version and optional coverage tools

inputs:
  git-version:
    description: Git version to install (or "latest")
    required: false
    default: latest
  coverage:
    description: Enable coverage tools
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Git ${{ inputs.git-version }}
      if: inputs.git-version != 'latest' && runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev
        GIT_VERSION="${{ inputs.git-version }}"
        curl -sL "https://github.com/git/git/archive/v${GIT_VERSION}.tar.gz" \
          | tar xz
        cd "git-${GIT_VERSION}"
        make prefix=/usr/local all -j"$(nproc)"
        sudo make prefix=/usr/local install
        git --version
    - name: Set up Ruby
      if: inputs.coverage == 'true'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
    - name: Install coverage tools
      if: inputs.coverage == 'true'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y libxml2-utils
        gem install bashcov
